### ISSUE TITLE
The program should use the download folder by default

### ISSUE THREAD

**Issue by Wiltoga** [AvaN0x/YoutubeDownloader#1]
When opening, it currently uses the current working directory. Not cool.

**Comment by AvaN0x** [comment]
Yes, I want it too. I tried to do it, but it was a bit tricky, so I decided to do it later for a future release

**Comment by AvaN0x** [comment]
Here you are
[Commit](https://github.com/AvaN0x/YoutubeDownloader/commit/ccb1dc634f64943194a54f57a7ba6495f64226f4)
